index.adoc
trident-managing-k8s/upgrade-operator.adoc
trident-rn.adoc

Added version information to landing page and release notes.

Gh issue 18

---

earlier-versions.adoc
trident-rn.adoc
trident-use/gcp.adoc

release notes & earlier version page updates

release notes & earlier version page updates

---

trident-use/vol-snapshots.adoc

added note for GKE snapshot-controller per issue #27

added note for GKE snapshot-controller

---

trident-get-started/kubernetes-deploy-operator.adoc

Added --create-namespace parm to helm install per #38

Added --create-namespace parm to helm install

---

troubleshooting.adoc

Orchestrator debug logging correction/details per wonderland PR #39

 Orchestrator debug logging correction/details per wonderland PR#39

---

legal.adoc
trident-concepts/intro.adoc

Added links to Astra product family & link to Trident open source notices on github

Issue #28 & update to legal notices

---

trident-use/anf.adoc

Includes content for:
* Required location field
* New filter parameters & their format
* New unix permissions option

Doc changes for ANF driver overhaul

---

trident-concepts/intro.adoc
trident-use/ads.adoc
trident-use/sidebar.yml

New Trident ADS driver topic & related reference changes

Added  Trident ADS driver topic & refs

---

trident-get-started/kubernetes-deploy-operator.adoc
trident-get-started/requirements.adoc

Update supported OS, OpenShift Note, & min K8s version

---

trident-use/anf.adoc

Reverts NetAppDocs/trident#47 to save as draft until 22.01

Revert "Doc changes for ANF driver overhaul"

---

trident-use/anf.adoc

This has been in RTD for ~10 months but was somehow not brought forward.

Add snapshotDir content to ANF doc

---

trident-use/anf.adoc

Includes content for:
* Required location field
* New filter parameters & their format
* New unix permissions option

Restored 22.01 ANF changes

---

trident-get-started/kubernetes-customize-deploy.adoc
trident-reference/trident-cl.adoc
trident-use/ontap-nas.adoc
trident-use/ontap-san.adoc

Fixes issues #66 & #73

---

trident-concepts/intro.adoc

Changed "Astra data documentation" to "Astra Data Store documentation" per @amgrissino

Corrected typo per AMG

---

trident-reference/objects.adoc

Add attributes to Kubernetes attributes table & updated YAML example to close #76

Add Kubernetes attributes table & update example

---

trident-docker/stor-config.adoc

Fixes https://github.com/NetAppDocs/trident/issues/86

Small typo limitVolumeSizee (Issue 86)

---

trident-use/trident-fsx.adoc

This PR replaces https://github.com/NetAppDocs/trident/pull/82
Final approved by @balaramesh

Issue 82: Add warning banner to FSx documentation

---

trident-use/ads.adoc

Added collapsible blocks to backend config examples.

Adding collapsible blocks

---

trident-use/project.yml

[DOC-4096](https://jira.ngage.netapp.com/browse/DOC-4096)
Added Astra family breadcrumb to navigation

added astra family breadcrumb

---

trident-get-started/requirements.adoc

Added Anthos support for 1.10

---

trident-docker/stor-config.adoc
trident-docker/volume-driver-options.adoc
trident-get-started/kubernetes-deploy-operator.adoc
trident-use/ads.adoc
trident-use/trident-fsx.adoc

https://github.com/NetAppDocs/trident-internal/pull/50

Helm install instructions update 

---

trident-use/csi-topology.adoc

Issue 92: updated availability zone language

---

trident-get-started/kubernetes-customize-deploy.adoc

To address PR: https://github.com/NetApp/trident/issues/708

Include an example for nodeSelectors

---

trident-use/element.adoc

Creating PR for https://github.com/NetAppDocs/trident/issues/95

useCHAP is forced to true for solidfire-san

---

trident-use/ontap-nas-prep.adoc

This PR is to address https://github.com/NetApp/trident/issues/705. 
This change must be backported to all available versions of the Trident docs.

ONTAP Cert auth example update

---

trident-docker/collect-logs-docker.adoc

Minor updates for accessibility compliance.

Added heading for accessibility project

---

trident-use/trident-fsx.adoc

PR 145: Clarify fsxadmin limitations

---

trident-get-started/kubernetes-deploy-operator.adoc

Fixes #147 
Added new text to clarify how Trident operator handles installation using Helm chart versus manually.

Clarified Trident operator installation options

---

project.yml

Adds link to Astra family page from sidebar.

Added new prod fam keyword

---

trident-use/anf.adoc

156 serviceLevel is duplicated in backend config

---

trident-get-started/kubernetes-deploy.adoc

This goes live when the June K8s release goes live to support the new upgrade capabilities in Cloud Manager K8s.

Added note about Cloud Manager Trident upgrade

---

.github/workflows/netappdocs-ci.yml
trident-get-started/kubernetes-customize-deploy.adoc
trident-get-started/kubernetes-deploy-operator.adoc
trident-get-started/kubernetes-deploy.adoc
trident-get-started/requirements.adoc
trident-managing-k8s/upgrade-operator.adoc
trident-reference/objects.adoc
trident-use/vol-snapshots.adoc

Updated minimum version to 1.18 up to 1.24

Updated K8s minimum to 1.18

---

trident-get-started/kubernetes-deploy-operator.adoc

Issue 163: Helm version update

---

trident-get-started/requirements.adoc

Fixed broken table

---

trident-reference/pod-security.adoc
trident-reference/sidebar.yml

Added details for Trident security standards. Fixes #172

Issue 172: Add details for SCC & PSP/PSS

---

earlier-versions.adoc

Fixes https://github.com/NetAppDocs/trident-2204/issues/2

2204 earlier versions

---

trident-get-started/kubernetes-deploy-operator.adoc
trident-get-started/kubernetes-deploy-tridentctl.adoc

Updated name of GH section from "Downloads" to "Assets"
Fixes #152

Issue 152: Update GH section title

---

trident-use/trident-fsx.adoc

Per #122 on /trident-internal fixed broken link & removed external linking for internal hyperlinks

Broken link

---

trident-get-started/requirements.adoc

Updated snapshotter version in note block to v6.x

Snapshotter version hotfix

---

trident-get-started/requirements.adoc

Updated OpenShift version support to: 4.8, 4.9, 4.10, 4.11
Fixes #196

Updated OCP to 4.11

---

trident-get-started/kubernetes-deploy-operator.adoc
trident-reco/storage-config-best-practices.adoc
trident-reference/objects.adoc
trident-use/vol-snapshots.adoc

Removed copy commands from snippets.

Copy command changes

---

_index.yml
trident-use/sidebar.yml

Issue 202: Move prep worker node section

---

trident-get-started/kubernetes-deploy.adoc

Updated references to Cloud Manager to BlueXP

BlueXP launch

---

faq.adoc
trident-reference/ports.adoc

Issue 208: Fix broken link

---

trident-managing-k8s/upgrade-operator.adoc

Page: [Upgrade with the operator](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html)
This link is not working: https://docs.netapp.com/us-en/trident/trident-deploy-k8s/kubernetes-customize-deploy.html (content is in a different section)

Resolved broken link

---

trident-use/ontap-nas-examples.adoc
trident-use/ontap-san-examples.adoc

Removed tech preview note from MCC switchover. MCC switchover is GA in 22.10. 
Fixes #212

Issue 212: Removed MCC tech preview note

---

trident-docker/prereqs-docker.adoc

Issue 215: Update iSCSI commands for Docker plugin

---

trident-get-started/kubernetes-deploy-operator.adoc
trident-managing-k8s/upgrade-operator.adoc
trident-reference/objects.adoc
trident-use/csi-topology.adoc

- Updated Help install commands
- Updated K8s refs to 1.25 or replaced with redirect to Requirements where it makes sense

Update Helm install command

---

trident-docker/deploy-docker.adoc

Fixes #218 
Removed hard-coded reference to version level in Docker command line.

Issue 218: Removed outdated version 

---

trident-get-started/kubernetes-deploy-operator.adoc
trident-managing-k8s/downgrade-trident.adoc
trident-managing-k8s/upgrade-operator.adoc

Updated references to bundle.yaml for 22.10 to reflect new bundle YAML versions based on K8s version (1.25 or lower than 1.25).
Fixes #225 
Fixes #225 
Fixes #227

Issues 225 226 227: Updates related to bundle YAML for 22.10

---

trident-get-started/requirements.adoc
trident-reference/sidebar.yml

Issue 228: Astra ports link is 404

---

trident-use/vol-snapshots.adoc

- Reorganized topic to move creating snapshot controller & CRDs to bottom (because users shouldn't have to scroll through this content to get to the steps; they can access if needed). This is in response to issue https://github.com/NetAppDocs/trident/issues/231)
- Removed references and snippets related to v1beta1 because v1 went GA in K8s 1.20 and we don't support 1.19 and lower beginning in 22.10.
Fixes #231

Issue 231: Work with snapshots reorg

---

trident-concepts/virtual-storage-pool.adoc

Issue 237: number of operators supported by virtual storage pools

---

trident-use/ontap-nas-examples.adoc

Added space between lines to make ontap-nas-economy limitation more obvious. Fixes #240

Issue 240: Made ontap-nas-economy limitation more obvious (editorial change)

---

trident-reference/objects.adoc

Removed references to `esries-iscsi` driver that was formally removed in 22.04. Fixes #241

Issue 241: Remove eseries-iscsi driver reference

---

trident-use/ontap-nas-examples.adoc

- Removed dupe parameters from NAS options table
- Fixed broken rows
Fixes #246

Issue 246: Remove duplicate parameters

---

_index.yml
project.yml

- Remove `platform` from project.yml
- Remove line with `**` from index.yml

Issue 200 (Admin): Linter error correction

---

trident-docker/stor-config.adoc
trident-use/ontap-nas-examples.adoc
trident-use/trident-fsx-examples.adoc
trident-use/trident-fsx-prep.adoc

Added `mixed` option to `securityStyle` parameter for FSx and NAS.

Issue 210: Add `mixed` type 

---

trident-get-started/kubernetes-deploy-operator-mirror.adoc
trident-get-started/kubernetes-deploy-operator.adoc

Replaced `io_tridentorchestrators_crd_<version>.yaml` with `io_tridentorchestrators_crd_post1.16.yaml`

Issue 265: Replace version variable with file name

---

trident-managing-k8s/upgrade-operator.adoc

Issue 254: Clarify upgrade with operator

---

trident-concepts/architecture.adoc
trident-get-started/kubernetes-customize-deploy.adoc
trident-use/anf-prep.adoc

Updated prereqs for Azure NetApp Files backends for SMB volumes. Fixes #283

Issue 283: Updates to SMB for Azure NetApp Files

---

trident-use/ontap-nas-prep.adoc

Update command from `tridentctl backend update` to `tridentctl update backend`.

Issue 291: Update command

---

trident-reco/integrate-trident.adoc
trident-use/anf.adoc
trident-use/ontap-nas-prep.adoc
trident-use/ontap-san-examples.adoc

PR 288: Corrected destination URL 

---

trident-concepts/ontap-drivers.adoc

Added RWOP to the supported access modes for ONTAP drivers.

Issue 311: Add RWOP to supported access modes

---

trident-get-started/kubernetes-deploy-operator-mirror.adoc
trident-get-started/kubernetes-deploy-operator.adoc

Added additional steps to create and deploy the kustomization.yaml.

Issue 321: Add steps to create kustomization.yaml

---

trident-use/ontap-nas-examples.adoc
trident-use/ontap-nas-prep.adoc
trident-use/ontap-nas.adoc
trident-use/ontap-san-prep.adoc
trident-use/trident-fsx-examples.adoc
trident-use/trident-fsx-prep.adoc

- Added SMB requirements and prep for SMB on `ontap-nas`
- Added SMB minimal configuration for SMB on `ontap-nas`

Issue 310: Clarify SMB support on ontap-nas

---

trident-concepts/ontap-drivers.adoc

Added SMB to ONTAP drivers table for ontap-nas-x drivers.

Issue 324: Add SMB to ONTAP drivers table

---

trident-get-started/requirements.adoc

Updated the minimum K8s version in the requirements table.

Issue 335: Correct minimum K8s version

---

trident-use/vol-import.adoc

Add clarification that volume import is not supported on `ontap-san-economy`.

Issue 332: Add vol import not supported on ontap-san-economy

---

trident-use/trident-fsx.adoc

Issue 345: Fix hyperlinks

---

trident-managing-k8s/uninstall-trident.adoc
troubleshooting.adoc

- Consolidated all CRD removal steps in Troubleshooting
- Added CRD removal command for Helm

Consolidate CRD removal--hotfix

---

trident-use/backend_ops_kubectl.adoc
trident-use/ontap-nas-examples.adoc
trident-use/ontap-san-examples.adoc

added details & config example for seamless MCC switch over/back.

Internal Issue 290: Add details for MCC switch over 

---

trident-docker/deploy-docker.adoc
trident-get-started/requirements.adoc
trident-install/kubernetes-customize-deploy.adoc
trident-install/kubernetes-deploy-helm-mirror.adoc
trident-install/kubernetes-deploy-helm.adoc
trident-install/kubernetes-deploy-operator-mirror.adoc
trident-install/kubernetes-deploy-operator.adoc
trident-install/kubernetes-deploy-tridentctl.adoc
trident-managing-k8s/upgrade-operator-overview.adoc
trident-managing-k8s/upgrade-operator.adoc
trident-rn.adoc

- Updated 23.07.0 to 23.07.1 in file references
- Updated RN to reflect fixe in 23.07.1
- Updated Upgrade overview to call out "rolling update" support

23.07.1 release updates

---

trident-use/ontap-nas.adoc
trident-use/ontap-san.adoc

Clarify the description of `ontap-nas-economy` limitations & add link to ONTAP PVC limits.

Issue 359: Clarify ACC driver support

---

trident-install/kubernetes-customize-deploy.adoc

Table cells were deleted during conflict resolution. Applying fix back to 23.04.

Admin: Restore missing table content

---

project.yml

Admin 313: Remove sidebar label keyword and value

---

trident-managing-k8s/uninstall-trident.adoc

Added `kubectl delete -f deploy/<bundle.yaml> -n <namespace>` to uninstall process.

Issue 391: Add kubectl delete -f

---

earlier-versions.adoc
project.yml

Version selector update

---

get-help.adoc
trident-rn.adoc

Updated the get help page to remove references to releasees prior to 21.07.

Updated the get help page

---

trident-managing-k8s/upgrade-operator.adoc

Updated the helm install example

434 upgrade helm install

---

trident-use/anf.adoc

Updated the Cloud Identity for AKS section

Trident aks hotfix

---

trident-get-started/requirements.adoc

Updated to fix https://github.com/NetAppDocs/trident/issues/433

433 csi resizer

---

trident-use/worker-node-prep.adoc

Updated to remove reboot step after ISCSi configuration.

Updated to remove reboot step

---

trident-protect/trident-protect-cli.adoc
trident-protect/trident-protect-installation.adoc

HOTFIX: Fixes for Trident public repo GH issues 500, 501, 502.

---

trident-protect/trident-protect-requirements.adoc

HOTFIX: Added a note for snapshot controllers to the requirements for ASTRADOC-565.

---

trident-protect/trident-protect-appvault-custom-resources.adoc

HOTFIX: Improvements for the AppVault instructions for Trident protect.

---

trident-use/backend_ops_tridentctl.adoc

Updated to resolve https://github.com/NetAppDocs/trident/issues/630

630 delete trident backend
